name: Daily Auto Run (Generate → Refresh)

on:
  schedule:
    # รันทุกวันเวลา 00:00 UTC = 07:00 เวลาไทย
    - cron: '0 0 * * *'
  workflow_dispatch:  # เผื่อกดรันเองได้ด้วย

jobs:
  daily-tasks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run generate_dataset.py
        run: |
          echo "Running generate_dataset.py..."
          python generate_dataset.py

      - name: Run refresh_all.py
        run: |
          echo "Running refresh_all.py..."
          python refresh_all.py
